### ISSUE TITLE
Under recent chrome the canvas is not clearing properly

### ISSUE THREAD

**Issue by tissak** [cykod/AlienInvasion#1] opened 2012-10-07 22:39 UTC
Chrome: Version 22.0.1229.79

![broken canvas](https://img.skitch.com/20121008-bqdyp29rn2t6k7andyqhaya1yw.jpg)

**Comment by cykod** [comment] 2012-10-08 13:30
Seems actually to be a problem related to the cache manifest affecting creating offscreen canvas elements (specifically the Starfield, which does the clearing) in window.load

running `startGame();` from the console fixes the problem.

Work around: remove cache manifest.

Will see if there's a bug in Chrome or if there's a simple test case that triggers it.

**Comment by cykod** [comment] 2013-04-13 21:16
Actually this was unrelated to cache manifest - caused by the change in the callback time to requestAnimationFrame (http://code.google.com/p/chromium/issues/detail?id=165505)

Fixed in 5e2c3722ddfe94683e86dff1b2df1116203c1328

**Closed as completed by cykod** 2013-04-13 21:16 UTC
